// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-CpqMVPpIOYK0WFy0hTI8PT1s3W6DOAQ',
    appId: '1:321276986165:web:17abad6d35d38ae6be827c',
    messagingSenderId: '321276986165',
    projectId: 'fir-a41f4',
    authDomain: 'fir-a41f4.firebaseapp.com',
    storageBucket: 'fir-a41f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMcsXacsS96U8Cc15_duglBGRhIF-da8',
    appId: '1:321276986165:android:5a2fa069fc1a2506be827c',
    messagingSenderId: '321276986165',
    projectId: 'fir-a41f4',
    storageBucket: 'fir-a41f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2otLZXZj4UHMXxsMw8EsBd97qBspewcY',
    appId: '1:321276986165:ios:e9b527852b3d679fbe827c',
    messagingSenderId: '321276986165',
    projectId: 'fir-a41f4',
    storageBucket: 'fir-a41f4.firebasestorage.app',
    iosBundleId: 'com.example.hadieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2otLZXZj4UHMXxsMw8EsBd97qBspewcY',
    appId: '1:321276986165:ios:e9b527852b3d679fbe827c',
    messagingSenderId: '321276986165',
    projectId: 'fir-a41f4',
    storageBucket: 'fir-a41f4.firebasestorage.app',
    iosBundleId: 'com.example.hadieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-CpqMVPpIOYK0WFy0hTI8PT1s3W6DOAQ',
    appId: '1:321276986165:web:4fc6478791fde4a1be827c',
    messagingSenderId: '321276986165',
    projectId: 'fir-a41f4',
    authDomain: 'fir-a41f4.firebaseapp.com',
    storageBucket: 'fir-a41f4.firebasestorage.app',
  );

}